### ISSUE TITLE
Change 68 Middle Street logo

### ISSUE THREAD

**Issue by vivdoc** [alexandtheweb/springforward#10]
Tessa has asked us to replace the 68 Middle St logo with a new version.

The files can be found in this Dropbox folder:
https://www.dropbox.com/sh/wjpk9c7bicuw62j/AADeqXZVdooHHKFqepizJ5KDa?dl=0

**Comment by Rosa-Fox** [comment]
Hi, 

I sent Alex a pull request. I used the large logo as I thought it kind of looked ok with AMEX's being large and also 68MS are helping out loads... but let me know if you think one the same size as the previous would look better.

**Comment by alexandtheweb** [comment]
@vivdoc @Rosa-Fox Geez guys, I wasn't getting email alerts for pull requests - only just saw this! Silly me - merged!
