### ISSUE TITLE
Add MailChimp signup form (footer)

### ISSUE THREAD

**Issue by alexandtheweb** [alexandtheweb/springforward#3]
Will share login details

**Comment by notthepoint** [comment]
are you able to email me the login details?

**Comment by vivdoc** [comment]
Where are we at with this issue? Would be great to have this in the site as we're getting lots of traffic

**Comment by notthepoint** [comment]
Hey! Sorry Github still confuses me sometimes. There is a pull request for it .. the signup form should work, but I believe it might be in want of some styling tweaks. :)

**Comment by vivdoc** [comment]
Hey. Any chance we can get this done this week? Thanks!

**Comment by alexandtheweb** [comment]
@vivdoc Finally merged in! Have a look in the footer - not sure how much prominence you wanted to give it?

**Comment by alexandtheweb** [comment]
@vivdoc I reckon it makes more sense to add the sign up form to the "Get involved" section, as the copy in that bit is becoming less relevant now

**Comment by vivdoc** [comment]
@alexandtheweb I like the idea of replacing the 'Get involved' section with the sign up. Maybe just swap places?
Can we change the button label to 'Sign up' and place it in the same row that the text fields?
Thanks!

**Comment by alexandtheweb** [comment]
@vivdoc How about 
![screen shot 2015-03-25 at 18 25 30](https://cloud.githubusercontent.com/assets/839958/6832136/66267154-d31c-11e4-92bb-4af697cfffc7.png)

**Comment by vivdoc** [comment]
@alexandtheweb I rather leave them as separate sections as 'Stay in touch' is about signing up for festival news and not necessary for people who want to get involved organising or volunteering.

**Comment by alexandtheweb** [comment]
OK, I can push the change tomorrow morning.
