### ISSUE TITLE
Add American Express sponsor logo

### ISSUE THREAD

**Issue by alexandtheweb** [alexandtheweb/springforward#5]

**Comment by alexandtheweb** [comment]
@Rosa-Fox here's the latest Sponsor info from VIv! I'll forward her email as well.

"
Gold sponsor: American Express www.americanexpress.com/uk/

Silver sponsors:
​​Firefly fireflylearning.com (Curiosity Hub)
Brightwave www.brightwave.co.uk (SheSays)
Hatch thisishatch.co.uk (Ladies That UX)
Madgex and/or Brandwatch? Tbc? (300 Seconds)
Firefly logos attached and the Amex stuff is in the Dropbox.

I'll ask Emma for the Hatch logo and Rifa for the Brightwave one."

**Comment by Rosa-Fox** [comment]
Thanks, have added Amex... I looked in Dropbox but the logo had an error so I got one from the internet... let me know when you get the other logos and I will add them. I can use images from internet for time being, though I might have to finish it tomorrow as have something I need to get done and going to London straight after work. The Amex addition is on the sponsors branch.

**Comment by Rosa-Fox** [comment]
OK I have added Brightwave and Firefly logos. Was going to wait for the Hatch and either Madgex/Brandwatch logos before sending a PR, but if they take a while I guess we can just put it up as it is (if you two think it is ok) and then add the others when we get them.

**Comment by Rosa-Fox** [comment]
Also think we should put 68 Middle Street's logo on there to show some appreciation for the venue.
